@HOST = 127.0.0.1
@PREFIX = /api
@TOKEN = Bearer {{Me_put.response.body.cyToken}}

###
# @name apiInfo_get
GET http://{{HOST}}{{PREFIX}}

###
# @name apiInfo_post
POST http://{{HOST}}{{PREFIX}}
Content-Type: application/json

{
  "uuid": "{{$guid}}",
  "time": "{{$localDatetime iso8601}}"
}

###
# @name Me_get
GET http://{{HOST}}{{PREFIX}}/Me

###
# @name Me_put
PUT http://{{HOST}}{{PREFIX}}/Me
Content-Type: application/json

{
  "username": "cywang@email.com",
  "password": "123456"
}

###
# @name Me_del
DELETE http://{{HOST}}{{PREFIX}}/Me

###
# @name User_post
POST http://{{HOST}}{{PREFIX}}/User
Content-Type: application/json

{
  "name": "CY Wang",
  "username": "cywang@email.com",
  "password": "123456"
}
